'use client';

import { useEffect, useMemo, useState } from 'react';
import AnatomyScene from './scene';
import type { AtlasSelection, AtlasStatus } from './scene';
import { DEFAULT_VISIBLE, SYSTEMS, type Atlas, type Concept, type SceneState, type SystemId } from './anatomy';

const initialState: SceneState = { explode: 0, visible: [...DEFAULT_VISIBLE, 'integumentary'], selected: [], hidden: [], severity: {}, isolate: false, view: 'three-quarter', rotate: false, reset: 0, fit: 0 };

export function HumanAtlasExplorer({ onSelect, severity = {} }: { onSelect?: (selection: AtlasSelection) => void; severity?: Record<string, number> }) {
  const [atlas, setAtlas] = useState<Atlas | null>(null);
  const [state, setState] = useState<SceneState>(initialState);
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState<Concept | null>(null);
  const [error, setError] = useState('');
  const [progress, setProgress] = useState(0);
  const [status, setStatus] = useState<AtlasStatus>('loading');
  useEffect(() => { fetch('/api/anatomy/human-atlas/assets').then(async (response) => { if (!response.ok) { const body = await response.json().catch(() => null) as { code?: string } | null; throw new Error(`Human Atlas assets request failed (${response.status}${body?.code ? `: ${body.code}` : ''}).`); } return response.json() as Promise<Array<{ kind: 'MANIFEST' | 'GEOMETRY_CHUNK'; assetIndex: number; url: string }>>; }).then(async (assets) => { const manifestAsset = assets.find((asset) => asset.kind === 'MANIFEST'); if (!manifestAsset) throw new Error('Human Atlas manifest asset is missing.'); const loaded = await fetch(manifestAsset.url); if (!loaded.ok) throw new Error(`Human Atlas manifest request failed (${loaded.status}).`); const manifest = await loaded.json() as Atlas; manifest.chunks = manifest.chunks.map((chunk, index) => ({ ...chunk, gzip: assets.find((asset) => asset.kind === 'GEOMETRY_CHUNK' && asset.assetIndex === index)?.url ?? chunk.gzip })); setAtlas(manifest); }).catch((reason: unknown) => { setStatus('error'); setError(reason instanceof Error ? reason.message : 'Human Atlas could not be loaded.'); }); }, []);
  const results = useMemo(() => { if (!atlas) return []; const term = query.trim().toLowerCase(); return atlas.concepts.filter((concept) => !term || concept.name.toLowerCase().includes(term) || concept.id.toLowerCase().includes(term)).slice(0, 60); }, [atlas, query]);
  const choose = (concept: Concept) => { setSelected(concept); setState((current) => ({ ...current, selected: concept.elements, isolate: false })); };
  const toggleSystem = (id: SystemId) => setState((current) => ({ ...current, visible: current.visible.includes(id) ? current.visible.filter((item) => item !== id) : [...current.visible, id], selected: [], isolate: false }));
  const reset = () => { setState({ ...initialState, reset: state.reset + 1 }); setSelected(null); };
  return <div data-testid="human-atlas-root" data-atlas-status={status} className="relative min-h-[calc(100vh-8rem)] overflow-hidden rounded-2xl bg-[#f2f3f3]">
    {atlas ? <AnatomyScene atlas={atlas} state={{ ...state, severity }} onSelect={(selection) => { onSelect?.(selection); const part = atlas.parts.find((item) => item.id === selection.sourcePartId); if (part) choose({ id: part.conceptId, name: part.name, elements: [part.id] }); }} onProgress={setProgress} onError={(message) => { setStatus('error'); setError(message); }} onStatus={setStatus} /> : null}
    <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-white/20 via-transparent to-black/5" />
    <header className="absolute left-5 top-5 z-10 max-w-sm rounded-xl bg-white/85 p-4 shadow-lg backdrop-blur"><p className="text-xs uppercase tracking-[0.18em] text-text-secondary">Primary anatomy source</p><h1 className="font-serif text-2xl text-text-primary">Human Atlas</h1><p className="text-sm text-text-secondary">BodyParts3D 4.0 · {atlas?.parts.length.toLocaleString() ?? '2,234'} source parts · 15 systems</p></header>
    <aside className="absolute right-5 top-5 z-10 w-72 rounded-xl bg-white/90 p-4 shadow-lg backdrop-blur"><label className="text-sm font-medium">Search anatomical concepts<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Femur, heart…" className="mt-2 w-full rounded border border-border bg-white px-3 py-2" /></label><div className="mt-3 max-h-52 overflow-auto">{results.map((concept) => <button key={concept.id} type="button" onClick={() => choose(concept)} className="block w-full rounded px-2 py-1.5 text-left text-sm hover:bg-brand/10">{concept.name}<span className="ml-2 text-xs text-text-secondary">{concept.elements.length}</span></button>)}</div><div className="mt-4 border-t border-border pt-3"><p className="mb-2 text-xs font-medium uppercase tracking-wide text-text-secondary">Systems</p>{SYSTEMS.map((system) => <label key={system.id} className="flex items-center gap-2 py-1 text-xs"><input type="checkbox" checked={state.visible.includes(system.id)} onChange={() => toggleSystem(system.id)} />{system.name}</label>)}</div></aside>
    <div className="absolute bottom-5 left-1/2 z-10 flex w-[min(52rem,calc(100%-2rem))] -translate-x-1/2 flex-wrap items-center gap-2 rounded-xl bg-white/90 p-3 shadow-lg backdrop-blur"><button type="button" className="rc-btn rc-btn-secondary" disabled={!state.selected.length} onClick={() => setState((current) => ({ ...current, isolate: !current.isolate }))}>{state.isolate ? 'Show all' : 'Isolate'}</button><button type="button" className="rc-btn rc-btn-secondary" disabled={!state.selected.length} onClick={() => setState((current) => ({ ...current, isolate: true, reset: current.reset + 1 }))}>Fit selected</button><button type="button" className="rc-btn rc-btn-secondary" disabled={!state.selected.length} onClick={() => setState((current) => ({ ...current, hidden: [...new Set([...current.hidden, ...current.selected])], selected: [], isolate: false }))}>Hide selected</button><button type="button" className="rc-btn rc-btn-secondary" disabled={!state.hidden.length} onClick={() => setState((current) => ({ ...current, hidden: [], reset: current.reset + 1 }))}>Unhide all</button><div className="flex gap-1" aria-label="Camera views">{(['front','back','side'] as const).map((view) => <button key={view} type="button" className="rounded border border-border px-2 py-1 text-xs" onClick={() => setState((current) => ({ ...current, view, reset: current.reset + 1 }))}>{view}</button>)}</div><label className="ml-auto flex min-w-48 items-center gap-2 text-xs">Exploded<input aria-label="Exploded view" type="range" min="0" max="1" step="0.01" value={state.explode} onChange={(event) => setState((current) => ({ ...current, explode: Number(event.target.value) }))} /></label><button type="button" className="text-xs text-info underline" onClick={reset}>Reset</button><a className="text-xs text-info underline" href="/docs/third-party/bodyparts3d.md">Source & attribution</a></div>
    {selected ? <div className="absolute bottom-24 left-5 z-10 max-w-xs rounded-xl bg-white/90 p-4 shadow-lg backdrop-blur"><p className="text-xs uppercase tracking-wide text-text-secondary">Source selection</p><h2 className="mt-1 font-medium">{selected.name}</h2><p className="text-xs text-text-secondary">{selected.id} · {selected.elements.length} mesh(es). Clinical annotation requires a separate verified RehabMIS mapping.</p></div> : null}<p className="absolute left-5 top-28 z-10 max-w-xs rounded bg-white/80 px-3 py-2 text-xs text-text-secondary shadow">{Object.keys(severity).length ? 'Heatmap: stored clinical severity only.' : 'No stored severity for this source view — geometry is neutral.'}</p>
    {progress < 100 && !error ? <p className="absolute bottom-5 right-5 z-10 rounded bg-white/85 px-3 py-2 text-xs shadow">Loading atlas… {progress}%</p> : null}{error ? <p role="alert" className="absolute bottom-5 right-5 z-10 rounded bg-danger/90 px-3 py-2 text-xs text-white">{error}</p> : null}
  </div>;
}
