'use client';
import { useState } from 'react';

type MediaItem = { id: string; kind: 'IMAGE' | 'VIDEO'; mimeType: string; originalFileName: string; title: string | null; description: string | null; capturedAt: string | null; createdAt: string; uploadedBy: string; sizeBytes: string };
export function PatientMediaGallery({ patientId, initialItems, initialTotal }: { patientId: string; initialItems: MediaItem[]; initialTotal: number }) {
  const [items] = useState(initialItems); const [total] = useState(initialTotal); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [urls, setUrls] = useState<Record<string, string>>({});
  async function upload(files: FileList | null) { if (!files?.length) return; setBusy(true); setMessage(''); let completed = 0; for (const file of Array.from(files)) { try { const kind = file.type.startsWith('video/') ? 'VIDEO' : 'IMAGE'; const start = await fetch(`/api/patient-media/${patientId}/uploads`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ kind, mimeType: file.type, sizeBytes: file.size, originalFileName: file.name }) }); if (!start.ok) throw new Error('start'); const intent = await start.json() as { mediaId: string; uploadUrl: string; requiredHeaders: Record<string, string> }; const put = await fetch(intent.uploadUrl, { method: 'PUT', headers: intent.requiredHeaders, body: file }); if (!put.ok) throw new Error('put'); const done = await fetch(`/api/patient-media/${patientId}/${intent.mediaId}/complete`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' }); if (!done.ok) throw new Error('complete'); completed += 1; } catch { setMessage(`${file.name}: не вдалося завантажити.`); } } setBusy(false); if (completed) window.location.reload(); }
  async function open(item: MediaItem) { const response = await fetch(`/api/patient-media/${patientId}/${item.id}/access`); if (response.ok) { const data = await response.json() as { url: string }; setUrls((current) => ({ ...current, [item.id]: data.url })); } }
  return <section className="rounded-md border border-border bg-surface p-5" aria-labelledby="patient-media-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 id="patient-media-title" className="font-serif text-lg text-text-primary">Фото та відео</h2><p className="mt-1 text-sm text-text-secondary">Приватні матеріали реабілітаційного процесу · {total} записів</p></div><label className="rc-btn rc-btn-primary cursor-pointer">{busy ? 'Завантаження…' : 'Додати медіа'}<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,video/mp4,video/quicktime,video/webm" multiple disabled={busy} onChange={(event) => { void upload(event.target.files); event.currentTarget.value = ''; }} /></label></div>{message ? <p role="alert" className="mt-3 text-sm text-danger">{message}</p> : null}<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <article key={item.id} className="overflow-hidden rounded border border-border"><button type="button" className="block w-full text-left" onClick={() => { void open(item); }}>{urls[item.id] ? item.kind === 'VIDEO' ? <video className="aspect-video w-full object-cover" controls preload="metadata" src={urls[item.id]} /> : <img className="aspect-video w-full object-cover" src={urls[item.id]} alt={item.title ?? item.originalFileName} /> : <div className="flex aspect-video items-center justify-center bg-surface-muted text-sm text-text-secondary">{item.kind === 'VIDEO' ? 'Відео' : 'Зображення'} · відкрити</div>}<div className="p-3"><p className="font-medium text-text-primary">{item.title ?? item.originalFileName}</p><p className="mt-1 text-xs text-text-secondary">{item.capturedAt ? new Date(item.capturedAt).toLocaleDateString() : 'Дата не вказана'} · {item.uploadedBy}</p>{item.description ? <p className="mt-2 text-sm text-text-secondary">{item.description}</p> : null}</div></button></article>)}</div>{!items.length ? <p className="mt-5 text-sm text-text-secondary">Медіа ще не додано.</p> : null}</section>;
}
