'use client';
import type { ResponsiblePractitionerResponse } from '@repo/contracts';
import { Button } from '@repo/ui/button';
import { useActionState, useEffect, useState } from 'react';
import { createCalendarBlockAction, type CalendarBlockFormState } from '../actions/calendar-block-actions';
const initial: CalendarBlockFormState = { error: null };
export function CalendarBlockCreateForm({ practitioners, timezone, onClose }: { practitioners: ResponsiblePractitionerResponse[]; timezone: string; onClose: () => void }) {
  const [state, action, pending] = useActionState(createCalendarBlockAction, initial); const [type, setType] = useState<'BREAK' | 'UNAVAILABLE' | 'DAY_OFF'>('BREAK');
  useEffect(() => { if (state.success) onClose(); }, [onClose, state.success]);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true" aria-labelledby="block-title"><form action={action} className="ui-surface w-full max-w-lg space-y-4 p-6"><div className="flex items-center justify-between"><h2 id="block-title" className="font-sans text-xl">Позначити недоступність</h2><button type="button" className="calendar-more-close" aria-label="Закрити" onClick={onClose}>×</button></div><div className="ui-segmented grid grid-cols-3"><button type="button" aria-pressed={type === 'BREAK'} onClick={() => setType('BREAK')}>Перерва</button><button type="button" aria-pressed={type === 'UNAVAILABLE'} onClick={() => setType('UNAVAILABLE')}>Недоступний час</button><button type="button" aria-pressed={type === 'DAY_OFF'} onClick={() => setType('DAY_OFF')}>Вихідний</button></div><input type="hidden" name="type" value={type}/><input type="hidden" name="timezone" value={timezone}/><label className="block text-xs text-text-secondary">Фізичний терапевт<select name="practitionerId" required defaultValue={practitioners.length === 1 ? practitioners[0]?.id : ''} className="field mt-1 w-full"><option value="" disabled>Оберіть фахівця</option>{practitioners.map((p) => <option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label><label className="block text-xs text-text-secondary">Дата<input name="date" type="date" required className="field mt-1 w-full"/></label>{type !== 'DAY_OFF' ? <div className="grid grid-cols-2 gap-3"><label className="text-xs text-text-secondary">Початок<input name="startTime" type="time" required className="field mt-1 w-full"/></label><label className="text-xs text-text-secondary">Кінець<input name="endTime" type="time" required className="field mt-1 w-full"/></label></div> : null}<label className="block text-xs text-text-secondary">Назва<input name="title" className="field mt-1 w-full"/></label><label className="block text-xs text-text-secondary">Примітка<textarea name="note" rows={3} className="field mt-1 w-full"/></label>{state.error ? <p role="alert" className="text-sm text-danger">{state.error}</p> : null}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>Скасувати</Button><Button type="submit" disabled={pending}>Зберегти</Button></div></form></div>;
}
