'use client';

import { useActionState, useMemo, useState } from 'react';
import type { ExerciseLibraryItem } from '@repo/contracts';
import { addEncounterExerciseAction, type EncounterExerciseState } from '../actions/encounter-exercise-actions';

const initial: EncounterExerciseState = { error: null, ok: false };
const keyOf = (value: string | Date) => { const date = new Date(value); return `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`; };

export function EncounterExerciseLogSection({ encounterId, exercises, logs, canCreate }: { encounterId: string; exercises: ExerciseLibraryItem[]; logs: any[]; canCreate: boolean }) {
  const [state, action, pending] = useActionState(addEncounterExerciseAction, initial);
  const [filter, setFilter] = useState(''); const [selectedDate, setSelectedDate] = useState(''); const [calendarOpen, setCalendarOpen] = useState(false);
  const [month, setMonth] = useState(() => { const date = new Date(logs[0]?.encounter?.startedAt ?? logs[0]?.createdAt ?? Date.now()); return new Date(date.getFullYear(), date.getMonth(), 1); });
  const sortedLogs = useMemo(() => [...logs].sort((a, b) => new Date(b.encounter?.startedAt ?? b.createdAt).getTime() - new Date(a.encounter?.startedAt ?? a.createdAt).getTime()), [logs]);
  const exerciseOptions = useMemo(() => {
    const library = exercises.filter((exercise) => logs.some((log) => log.exercise?.id === exercise.id)).map((exercise) => ({ value: exercise.id, label: exercise.name }));
    const custom = Array.from(new Set(logs.filter((log) => !log.exercise?.id && log.exerciseName).map((log) => log.exerciseName as string))).map((name) => ({ value: `custom:${name}`, label: name }));
    return [...library, ...custom];
  }, [exercises, logs]);
  const availableDays = useMemo(() => new Set(logs.map((log) => keyOf(log.encounter?.startedAt ?? log.createdAt))), [logs]);
  const visibleLogs = sortedLogs.filter((log) => (!filter || (filter.startsWith('custom:') ? `custom:${log.exerciseName}` === filter : log.exercise?.id === filter)) && (!selectedDate || keyOf(log.encounter?.startedAt ?? log.createdAt) === selectedDate));
  const monthDays = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const firstWeekday = (new Date(month.getFullYear(), month.getMonth(), 1).getDay() + 6) % 7;
  const chooseDay = (day: number) => { const date = new Date(month.getFullYear(), month.getMonth(), day); if (availableDays.has(keyOf(date))) { setSelectedDate(keyOf(date)); setCalendarOpen(false); } };
  return <section className="encounter-exercises ui-surface"><div className="encounter-exercises__header"><div><span className="encounter-exercises__eyebrow">Клінічна активність</span><h2>Вправи на прийомі</h2><p>Зафіксуй фактичне навантаження та результат заняття.</p></div><div className="encounter-exercises__count">{logs.length}<span>записів</span></div></div>
    {canCreate ? <form action={action} className="encounter-exercises__form"><input type="hidden" name="encounterId" value={encounterId}/><div className="encounter-exercises__exercise-choice"><label>Вправа з бібліотеки<select name="exerciseId"><option value="">Не обирати</option>{exercises.map((e)=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><span>або</span><label>Власна назва<input name="exerciseName" placeholder="Наприклад: ходьба по сходах"/></label></div><div className="encounter-exercises__metrics"><label>Підходи<input name="sets" type="number" min="0" placeholder="0"/></label><label>Повторення<input name="repetitions" type="number" min="0" placeholder="0"/></label><label>Вага, кг<input name="weightKg" type="number" min="0" step="0.1" placeholder="0"/></label><label>Тривалість, хв<input name="durationMinutes" type="number" min="0" placeholder="0"/></label></div><label className="encounter-exercises__note">Коментар фахівця<textarea name="specialistNote" placeholder="Що виконували, реакція пацієнта, рекомендації…" /></label>{state.error ? <p className="text-sm text-danger">{state.error}</p>:null}<button className="encounter-exercises__submit" disabled={pending}><span>＋</span>{pending ? 'Збереження…' : 'Додати вправу до прийому'}</button></form>:null}
    <details className="encounter-exercises__history" open><summary className="encounter-exercises__history-summary"><span>Історія вправ</span><span>{visibleLogs.length} записів</span></summary><div className="encounter-exercises__history-content"><div className="encounter-exercises__history-head"><div className="flex flex-wrap gap-2"><button type="button" className="rc-btn rc-btn-secondary" onClick={() => setCalendarOpen(true)}>Обрати дату</button>{selectedDate ? <button type="button" className="rc-btn rc-btn-ghost" onClick={() => setSelectedDate('')}>Показати всі</button> : null}</div><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">Усі вправи</option>{exerciseOptions.map((exercise) => <option key={exercise.value} value={exercise.value}>{exercise.label}</option>)}</select></div>{visibleLogs.length ? visibleLogs.map((log, index) => { const date = new Date(log.encounter?.startedAt ?? log.createdAt); const key = keyOf(date); const previous = visibleLogs[index - 1] ? keyOf(visibleLogs[index - 1].encounter?.startedAt ?? visibleLogs[index - 1].createdAt) : null; return <div key={log.id}>{key !== previous ? <div className="encounter-exercises__date-divider"><span>{date.toLocaleDateString('uk-UA', { dateStyle: 'long' })}</span></div> : null}<div className="encounter-exercise-card"><div className="encounter-exercise-card__title"><span>{log.exercise?.name ?? log.exerciseName}</span><small>{date.toLocaleTimeString('uk-UA',{hour:'2-digit',minute:'2-digit'})}</small></div><div className="encounter-exercise-card__stats">{[log.sets && `${log.sets} підх.`,log.repetitions && `${log.repetitions} повт.`,log.weightKg != null && `${log.weightKg} кг`,log.durationMinutes && `${log.durationMinutes} хв`].filter(Boolean).map((item)=><span key={item}>{item}</span>)}</div>{log.specialistNote?<p>{log.specialistNote}</p>:null}</div></div>; }):<p className="encounter-exercises__empty">Записів ще немає. Додай першу виконану вправу вище.</p>}</div></details>
    {calendarOpen ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" role="dialog" aria-modal="true" aria-label="Вибір дати вправ" onClick={() => setCalendarOpen(false)}><div className="w-full max-w-sm rounded-2xl border border-border bg-surface p-5 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h3 className="font-sans text-lg text-text-primary">Історія за датою</h3><button type="button" className="text-text-secondary" onClick={() => setCalendarOpen(false)}>×</button></div><div className="mb-4 flex items-center justify-between"><button type="button" className="rc-icon-btn" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}>‹</button><strong>{month.toLocaleDateString('uk-UA', { month: 'long', year: 'numeric' })}</strong><button type="button" className="rc-icon-btn" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}>›</button></div><div className="grid grid-cols-7 gap-1 text-center text-xs text-text-secondary">{['Пн','Вт','Ср','Чт','Пт','Сб','Нд'].map((day) => <span key={day} className="py-1">{day}</span>)}{Array.from({ length: firstWeekday }).map((_, index) => <span key={`empty-${index}`}/>)}{Array.from({ length: monthDays }, (_, index) => { const day = index + 1; const hasLogs = availableDays.has(keyOf(new Date(month.getFullYear(), month.getMonth(), day))); return <button key={day} type="button" disabled={!hasLogs} onClick={() => chooseDay(day)} className={`mx-auto flex h-9 w-9 items-center justify-center rounded-full text-sm ${hasLogs ? 'bg-brand/20 font-semibold text-brand hover:bg-brand hover:text-text-primary' : 'text-text-secondary/40'}`}>{day}</button>; })}</div><p className="mt-4 text-xs text-text-secondary">Обведені дати мають записи вправ.</p></div></div> : null}
  </section>;
}
