'use client';
import { useActionState, useState } from 'react';
import type { ExerciseLibraryItem } from '@repo/contracts';
import { addEncounterExerciseAction, type EncounterExerciseState } from '../actions/encounter-exercise-actions';
const initial: EncounterExerciseState = { error: null, ok: false };
export function EncounterExerciseLogSection({ encounterId, exercises, logs, canCreate }: { encounterId: string; exercises: ExerciseLibraryItem[]; logs: any[]; canCreate: boolean }) {
  const [state, action, pending] = useActionState(addEncounterExerciseAction, initial);
  const [filter, setFilter] = useState('');
  const sortedLogs = [...logs].sort((a, b) => {
    const aDate = new Date(a.encounter?.startedAt ?? a.createdAt).getTime();
    const bDate = new Date(b.encounter?.startedAt ?? b.createdAt).getTime();
    return bDate - aDate;
  });
  const visibleLogs = filter ? sortedLogs.filter((log) => log.exercise?.id === filter) : sortedLogs;
  return <section className="encounter-exercises ui-surface"><div className="encounter-exercises__header"><div><span className="encounter-exercises__eyebrow">Клінічна активність</span><h2>Вправи на прийомі</h2><p>Зафіксуй фактичне навантаження та результат заняття.</p></div><div className="encounter-exercises__count">{logs.length}<span>записів</span></div></div>
    {canCreate ? <form action={action} className="encounter-exercises__form"><input type="hidden" name="encounterId" value={encounterId}/><div className="encounter-exercises__exercise-choice"><label>Вправа з бібліотеки<select name="exerciseId"><option value="">Не обирати</option>{exercises.map((e)=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><span>або</span><label>Власна назва<input name="exerciseName" placeholder="Наприклад: ходьба по сходах"/></label></div><div className="encounter-exercises__metrics"><label>Підходи<input name="sets" type="number" min="0" placeholder="0"/></label><label>Повторення<input name="repetitions" type="number" min="0" placeholder="0"/></label><label>Вага, кг<input name="weightKg" type="number" min="0" step="0.1" placeholder="0"/></label><label>Тривалість, хв<input name="durationMinutes" type="number" min="0" placeholder="0"/></label></div><label className="encounter-exercises__note">Коментар фахівця<textarea name="specialistNote" placeholder="Що виконували, реакція пацієнта, рекомендації…" /></label>{state.error ? <p className="text-sm text-danger">{state.error}</p>:null}<button className="encounter-exercises__submit" disabled={pending}><span>＋</span>{pending ? 'Збереження…' : 'Додати вправу до прийому'}</button></form>:null}
    <div className="encounter-exercises__history"><div className="encounter-exercises__history-head"><h3>Історія вправ</h3><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">Усі вправи</option>{exercises.filter((exercise) => logs.some((log) => log.exercise?.id === exercise.id)).map((exercise) => <option key={exercise.id} value={exercise.id}>{exercise.name}</option>)}</select></div>{visibleLogs.length ? visibleLogs.map((log, index) => { const date = new Date(log.encounter?.startedAt ?? log.createdAt); const dateKey = `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`; const previousDate = visibleLogs[index - 1] ? new Date(visibleLogs[index - 1].encounter?.startedAt ?? visibleLogs[index - 1].createdAt) : null; const previousDateKey = previousDate ? `${previousDate.getFullYear()}-${previousDate.getMonth()}-${previousDate.getDate()}` : null; return <div key={log.id}>{dateKey !== previousDateKey ? <div className="encounter-exercises__date-divider"><span>{date.toLocaleDateString('uk-UA', { dateStyle: 'long' })}</span></div> : null}<div className="encounter-exercise-card"><div className="encounter-exercise-card__title"><span>{log.exercise?.name ?? log.exerciseName}</span><small>{date.toLocaleTimeString('uk-UA',{hour:'2-digit',minute:'2-digit'})}</small></div><div className="encounter-exercise-card__stats">{[log.sets && `${log.sets} підх.`,log.repetitions && `${log.repetitions} повт.`,log.weightKg != null && `${log.weightKg} кг`,log.durationMinutes && `${log.durationMinutes} хв`].filter(Boolean).map((item)=><span key={item}>{item}</span>)}</div>{log.specialistNote?<p>{log.specialistNote}</p>:null}</div></div>; }):<p className="encounter-exercises__empty">Записів ще немає. Додай першу виконану вправу вище.</p>}</div></section>;
}
