import { PERMISSIONS, type Permission, type StaffRole } from '@repo/contracts';

const ALL = Object.values(PERMISSIONS);

const ORGANIZATION_ADMIN: Permission[] = [
  PERMISSIONS.ORGANIZATION_READ,
  PERMISSIONS.ORGANIZATION_MANAGE,
  PERMISSIONS.STAFF_READ,
  PERMISSIONS.STAFF_MANAGE,
  PERMISSIONS.STAFF_CREATE,
  PERMISSIONS.STAFF_UPDATE,
  PERMISSIONS.STAFF_CHANGE_ROLE,
  PERMISSIONS.STAFF_DISABLE,
  PERMISSIONS.STAFF_ENABLE,
  PERMISSIONS.STAFF_SESSION_REVOKE,
  PERMISSIONS.PATIENT_READ_ADMIN,
  PERMISSIONS.PATIENT_CREATE,
  PERMISSIONS.PATIENT_UPDATE_ADMIN,
  PERMISSIONS.PATIENT_CHANGE_STATUS,
  PERMISSIONS.APPOINTMENT_READ,
  PERMISSIONS.APPOINTMENT_CREATE,
  PERMISSIONS.APPOINTMENT_UPDATE,
  PERMISSIONS.APPOINTMENT_CANCEL,
  PERMISSIONS.APPOINTMENT_CHANGE_STATUS,
  PERMISSIONS.ENCOUNTER_READ,
  PERMISSIONS.EXERCISE_READ,
  PERMISSIONS.DOCUMENT_READ_ADMIN,
  PERMISSIONS.DOCUMENT_WRITE,
  PERMISSIONS.AUDIT_READ,
];

const RECEPTIONIST: Permission[] = [
  PERMISSIONS.ORGANIZATION_READ,
  PERMISSIONS.PATIENT_READ_ADMIN,
  PERMISSIONS.PATIENT_CREATE,
  PERMISSIONS.PATIENT_UPDATE_ADMIN,
  PERMISSIONS.PATIENT_CHANGE_STATUS,
  PERMISSIONS.APPOINTMENT_READ,
  PERMISSIONS.APPOINTMENT_CREATE,
  PERMISSIONS.APPOINTMENT_UPDATE,
  PERMISSIONS.APPOINTMENT_CANCEL,
  PERMISSIONS.APPOINTMENT_CHANGE_STATUS,
  PERMISSIONS.EXERCISE_READ,
  PERMISSIONS.DOCUMENT_READ_ADMIN,
  PERMISSIONS.DOCUMENT_WRITE,
];

const REHABILITATION_SPECIALIST: Permission[] = [
  PERMISSIONS.ORGANIZATION_READ,
  PERMISSIONS.PATIENT_READ_ADMIN,
  PERMISSIONS.PATIENT_READ_CLINICAL,
  PERMISSIONS.APPOINTMENT_READ,
  PERMISSIONS.ENCOUNTER_READ,
  PERMISSIONS.ENCOUNTER_START,
  PERMISSIONS.ENCOUNTER_COMPLETE,
  PERMISSIONS.CLINICAL_NOTE_READ,
  PERMISSIONS.CLINICAL_NOTE_WRITE,
  PERMISSIONS.REHABILITATION_PLAN_READ,
  PERMISSIONS.REHABILITATION_PLAN_CREATE,
  PERMISSIONS.REHABILITATION_PLAN_UPDATE,
  PERMISSIONS.REHABILITATION_PLAN_ACTIVATE,
  PERMISSIONS.REHABILITATION_PLAN_PAUSE,
  PERMISSIONS.REHABILITATION_PLAN_COMPLETE,
  PERMISSIONS.REHABILITATION_PLAN_CANCEL,
  PERMISSIONS.REHABILITATION_GOAL_READ,
  PERMISSIONS.REHABILITATION_GOAL_WRITE,
  PERMISSIONS.EXERCISE_READ,
  PERMISSIONS.EXERCISE_PRESCRIPTION_READ,
  PERMISSIONS.EXERCISE_PRESCRIPTION_WRITE,
  PERMISSIONS.ASSESSMENT_READ,
  PERMISSIONS.ASSESSMENT_CREATE,
  PERMISSIONS.ASSESSMENT_UPDATE,
  PERMISSIONS.ASSESSMENT_COMPLETE,
  PERMISSIONS.ASSESSMENT_VOID,
  PERMISSIONS.MEASUREMENT_READ,
  PERMISSIONS.MEASUREMENT_WRITE,
  PERMISSIONS.ASSESSMENT_TEMPLATE_READ,
  PERMISSIONS.ANATOMY_READ,
  PERMISSIONS.ANATOMY_MODEL_READ,
  PERMISSIONS.BODY_ANNOTATION_READ,
  PERMISSIONS.BODY_ANNOTATION_CREATE,
  PERMISSIONS.BODY_ANNOTATION_UPDATE,
  PERMISSIONS.BODY_ANNOTATION_RESOLVE,
  PERMISSIONS.BODY_ANNOTATION_VOID,
  PERMISSIONS.PROGRESS_READ,
  PERMISSIONS.PATIENT_MONITORING_READ,
  PERMISSIONS.NOTIFICATION_SELF_READ,
  PERMISSIONS.NOTIFICATION_SELF_UPDATE,
  PERMISSIONS.CLINICAL_ALERT_READ,
  PERMISSIONS.CLINICAL_ALERT_ACKNOWLEDGE,
  PERMISSIONS.CLINICAL_ALERT_RESOLVE,
  PERMISSIONS.CLINICAL_TIMELINE_READ,
  PERMISSIONS.CLINICAL_REPORT_READ,
  PERMISSIONS.CLINICAL_REPORT_CREATE,
  PERMISSIONS.CLINICAL_REPORT_VOID,
  PERMISSIONS.DOCUMENT_READ_ADMIN,
  PERMISSIONS.DOCUMENT_READ_CLINICAL,
  PERMISSIONS.DOCUMENT_WRITE,
  PERMISSIONS.PATIENT_MEDIA_READ,
  PERMISSIONS.PATIENT_MEDIA_CREATE,
  PERMISSIONS.PATIENT_MEDIA_VOID,
  PERMISSIONS.PATIENT_MEDIA_DOWNLOAD,
];

const SYSTEM_ADMIN: Permission[] = [
  PERMISSIONS.ORGANIZATION_READ,
  PERMISSIONS.ORGANIZATION_MANAGE,
  PERMISSIONS.STAFF_READ,
  PERMISSIONS.STAFF_MANAGE,
  PERMISSIONS.EXERCISE_READ,
  PERMISSIONS.ANATOMY_READ,
  PERMISSIONS.ANATOMY_MODEL_READ,
  PERMISSIONS.ANATOMY_MODEL_MANAGE,
  PERMISSIONS.AUDIT_READ,
];

const PATIENT: Permission[] = [
  PERMISSIONS.PATIENT_PORTAL_SELF_READ,
  PERMISSIONS.REHABILITATION_PLAN_SELF_READ,
  PERMISSIONS.PROGRESS_SELF_READ,
  PERMISSIONS.DAILY_REPORT_SELF_READ,
  PERMISSIONS.DAILY_REPORT_SELF_CREATE,
  PERMISSIONS.DAILY_REPORT_SELF_UPDATE,
  PERMISSIONS.PATIENT_SYMPTOM_SELF_READ,
  PERMISSIONS.PATIENT_SYMPTOM_SELF_CREATE,
  PERMISSIONS.EXERCISE_COMPLETION_SELF_READ,
  PERMISSIONS.EXERCISE_COMPLETION_SELF_CREATE,
  PERMISSIONS.EXERCISE_COMPLETION_SELF_UPDATE,
  PERMISSIONS.NOTIFICATION_SELF_READ,
  PERMISSIONS.NOTIFICATION_SELF_UPDATE,
];

const ROLE_PERMISSIONS: Record<StaffRole, readonly Permission[]> = {
  SYSTEM_ADMIN,
  ORGANIZATION_ADMIN,
  RECEPTIONIST,
  REHABILITATION_SPECIALIST,
  PATIENT,
};

export function permissionsForRole(role: StaffRole): Permission[] {
  return [...ROLE_PERMISSIONS[role]];
}

export function roleHasPermission(role: StaffRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}

export function isKnownPermissionCatalogComplete(): boolean {
  return ALL.length > 0;
}
