import type { BodyAnnotationProgressResponse, ClinicalTimelineResponse, GoalProgressResponse, MeasurementTrendsResponse, PlanHistoryItem, ProgressSummaryResponse } from '@repo/contracts';
import { MeasurementChart } from './measurement-chart';

const status = (met: boolean | null) => met === null ? 'Немає зіставного вимірювання' : met ? 'Умова виконується' : 'Умова ще не виконується';
const Empty = ({ children }: { children: string }) => <p className="rounded-md border border-dashed border-border p-4 text-sm text-text-secondary">{children}</p>;

export function ProgressDashboard({ patientId, summary, measurements, goals, history, annotations, timeline, timelineNextHref }: { patientId: string; summary: ProgressSummaryResponse; measurements: MeasurementTrendsResponse; goals: GoalProgressResponse; history: PlanHistoryItem[]; annotations: BodyAnnotationProgressResponse; timeline: ClinicalTimelineResponse; timelineNextHref: string | null }) {
  return <div className="space-y-8">
    <section aria-labelledby="progress-summary"><h2 id="progress-summary" className="font-serif text-xl">Огляд</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      {[['Завершені контакти', summary.counts.completedEncounters], ['Оцінювання', summary.counts.completedAssessments], ['Ряди вимірювань', summary.counts.comparableMeasurementSeries], ['Активні цілі', summary.counts.activeGoals], ['Активні позначки', summary.counts.activeBodyAnnotations]].map(([label, value]) => <div key={label} className="rounded-md border border-border bg-surface p-4"><p className="text-xs text-text-secondary">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}
    </div>{summary.currentPlan ? <p className="mt-3 text-sm">Поточний план: <a href={`/app/rehabilitation-plans/${summary.currentPlan.id}`} className="text-info underline">{summary.currentPlan.title}, редакція {summary.currentPlan.revisionNumber}</a></p> : <p className="mt-3 text-sm text-text-secondary">Активного або призупиненого плану немає.</p>}</section>
    <section aria-labelledby="measurement-trends"><h2 id="measurement-trends" className="font-serif text-xl">Динаміка вимірювань</h2><p className="mt-1 text-sm text-text-secondary">Тільки числові значення із завершених неанульованих оцінювань. Лінія з’єднує фактичні точки без інтерполяції.</p><div className="mt-3 grid gap-4 lg:grid-cols-2">{measurements.series.length ? measurements.series.map((series) => <MeasurementChart key={series.key} series={series} />) : <Empty>Немає порівнюваних вимірювань за вибраний період.</Empty>}</div></section>
    <section aria-labelledby="goal-progress"><h2 id="goal-progress" className="font-serif text-xl">Прогрес цілей</h2><p className="mt-1 text-sm text-text-secondary">Умова цілі розраховується лише для перегляду і не змінює її статус.</p><div className="mt-3 space-y-3">{goals.goals.length ? goals.goals.map((goal) => <article key={goal.id} className="rounded-md border border-border bg-surface p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-medium">{goal.title}</h3><span className="text-xs text-text-secondary">{goal.status}</span></div><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-4"><div><dt className="text-text-secondary">Базове</dt><dd>{goal.baseline ? `${goal.baseline.value} ${goal.baseline.unit ?? ''}` : '—'}</dd></div><div><dt className="text-text-secondary">Поточне</dt><dd>{goal.current ? `${goal.current.value} ${goal.current.unit ?? ''}` : '—'}</dd></div><div><dt className="text-text-secondary">Ціль</dt><dd>{goal.target ? `${goal.target.operator} ${goal.target.value}${goal.target.upperValue === null ? '' : `–${goal.target.upperValue}`} ${goal.target.unit ?? ''}` : '—'}</dd></div><div><dt className="text-text-secondary">Перевірка</dt><dd>{status(goal.targetConditionMet)}</dd></div></dl></article>) : <Empty>У поточних редакціях планів немає цілей.</Empty>}</div></section>
    <section aria-labelledby="plan-history"><h2 id="plan-history" className="font-serif text-xl">Історія плану</h2><div className="mt-3 space-y-3">{history.length ? history.map((revision) => <article key={revision.revisionId} className="rounded-md border border-border bg-surface p-4"><h3 className="font-medium"><a className="text-info underline" href={`/app/rehabilitation-plans/${revision.planId}`}>{revision.title} · редакція {revision.revisionNumber}</a></h3><p className="mt-1 text-sm text-text-secondary">{new Date(revision.effectiveFrom ?? revision.createdAt).toLocaleString('uk-UA')} · {revision.planStatus}</p><p className="mt-2 text-sm">{revision.changeSummary ?? 'Опис змін не вказано.'}</p>{revision.diffFromPrevious ? <div className="mt-3 grid gap-2 text-xs sm:grid-cols-3"><p>Цілі: +{revision.diffFromPrevious.goals.added.length} / −{revision.diffFromPrevious.goals.removed.length} / змінено {revision.diffFromPrevious.goals.changed.length}</p><p>Вправи: +{revision.diffFromPrevious.exercises.added.length} / −{revision.diffFromPrevious.exercises.removed.length} / дозування {revision.diffFromPrevious.exercises.dosageChanged.length}</p><p>Фази: +{revision.diffFromPrevious.phases.added.length} / −{revision.diffFromPrevious.phases.removed.length} / змінено {revision.diffFromPrevious.phases.changed.length}</p></div> : null}</article>) : <Empty>Опублікованих редакцій плану немає.</Empty>}</div></section>
    <section aria-labelledby="body-history"><div className="flex flex-wrap items-end justify-between gap-2"><div><h2 id="body-history" className="font-serif text-xl">Історія позначок тіла</h2><p className="mt-1 text-sm text-text-secondary">Групування за анатомічною структурою і типом позначки.</p></div><a href={`/app/patients/${patientId}/body-map`} className="text-sm text-info underline">Відкрити карту тіла</a></div><div className="mt-3 overflow-x-auto">{annotations.groups.length ? <table className="w-full text-left text-sm"><thead><tr><th className="p-2">Структура</th><th>Тип</th><th>Активні</th><th>Вирішені</th><th>Остання інтенсивність</th></tr></thead><tbody>{annotations.groups.map((group) => <tr key={`${group.structure.id}:${group.type}`} className="border-t border-border"><td className="p-2"><a className="text-info underline" href={`/app/patients/${patientId}/body-map?structure=${encodeURIComponent(group.structure.id)}`}>{group.structure.name}</a></td><td>{group.type}</td><td>{group.activeCount}</td><td>{group.resolvedCount}</td><td>{group.latestSeverity ?? '—'}</td></tr>)}</tbody></table> : <Empty>Позначок за вибраний період немає.</Empty>}</div></section>
    <section aria-labelledby="clinical-timeline"><h2 id="clinical-timeline" className="font-serif text-xl">Клінічна хронологія</h2><div className="mt-3 space-y-2">{timeline.items.length ? timeline.items.map((item) => <article key={item.id} className="grid gap-2 rounded-md border border-border bg-surface p-3 sm:grid-cols-[140px_150px_1fr]"><time className="text-sm text-text-secondary">{new Date(item.occurredAt).toLocaleString('uk-UA')}</time><span className="text-xs font-medium">{item.category}</span><div><h3 className="text-sm font-medium">{item.link ? <a className="text-info underline" href={item.link}>{item.title}</a> : item.title}</h3>{item.description ? <p className="text-sm text-text-secondary">{item.description}</p> : null}</div></article>) : <Empty>Клінічних подій за вибраний період немає.</Empty>}</div>{timelineNextHref ? <a href={timelineNextHref} className="mt-4 inline-block text-sm text-info underline">Наступні події</a> : null}</section>
  </div>;
}
