ALTER TYPE "PatientStatus" ADD VALUE IF NOT EXISTS 'DRAFT';

CREATE TYPE "AppointmentPriceType" AS ENUM ('STANDARD', 'DISCOUNTED', 'CUSTOM', 'FREE', 'UNSPECIFIED');

ALTER TABLE "appointments"
  ADD COLUMN "priceType" "AppointmentPriceType" NOT NULL DEFAULT 'UNSPECIFIED',
  ADD COLUMN "priceAmountUah" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "currencyCode" VARCHAR(3) NOT NULL DEFAULT 'UAH';
