'use client';
import { useActionState, useState } from 'react';
import { createExerciseAction, type ExerciseCreateState } from '../actions/exercise-actions';
const initial: ExerciseCreateState = { error: null, ok: false };
export function ExerciseCreatePanel() {
  const [open, setOpen] = useState(false);
  const [state, action, pending] = useActionState(createExerciseAction, initial);
  return <><button type="button" className="rc-btn rc-btn-primary exercise-add-button" onClick={() => setOpen(true)}>＋ Додати вправу</button>{open ? <div className="exercise-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><section className="exercise-modal" role="dialog" aria-modal="true" aria-labelledby="exercise-modal-title"><div className="flex items-start justify-between gap-4 border-b border-border px-6 py-5"><div><p className="rc-kicker">Exercise library</p><h2 id="exercise-modal-title" className="mt-1 text-xl font-semibold">Нова вправа</h2></div><button type="button" className="rc-btn rc-btn-ghost" onClick={() => setOpen(false)} aria-label="Закрити">✕</button></div><form action={action} className="grid max-h-[75vh] gap-4 overflow-y-auto p-6 md:grid-cols-2"><label className="text-xs text-text-secondary">Код<input required name="code" placeholder="knee mobility 01" className="field mt-1" /></label><label className="text-xs text-text-secondary">Назва<input required name="name" placeholder="Мобілізація коліна" className="field mt-1" /></label><label className="text-xs text-text-secondary">Категорія<select name="category" defaultValue="OTHER" className="field mt-1"><option value="MOBILITY">Мобільність</option><option value="STRENGTH">Сила</option><option value="BALANCE">Баланс</option><option value="FUNCTIONAL">Функціональна</option><option value="BREATHING">Дихання</option><option value="OTHER">Інше</option></select></label><label className="text-xs text-text-secondary">Складність<select name="difficulty" className="field mt-1"><option value="">Не вказано</option><option value="FOUNDATIONAL">Базова</option><option value="INTERMEDIATE">Середня</option><option value="ADVANCED">Просунута</option></select></label><label className="text-xs text-text-secondary md:col-span-2">Опис<textarea required name="description" rows={2} className="field mt-1" /></label><label className="text-xs text-text-secondary md:col-span-2">Інструкції<textarea required name="instructions" rows={3} className="field mt-1" /></label><label className="text-xs text-text-secondary">Анатомічні ділянки<input name="anatomicalRegionCodes" placeholder="knee, hip" className="field mt-1" /></label><label className="text-xs text-text-secondary">Обладнання<input name="equipment" placeholder="mat, band" className="field mt-1" /></label>{state.error ? <p role="alert" className="text-sm text-danger md:col-span-2">{state.error}</p> : state.ok ? <p role="status" className="text-sm text-success md:col-span-2">Вправу створено.</p> : null}<div className="flex justify-end gap-3 md:col-span-2"><button type="button" className="rc-btn rc-btn-secondary" onClick={() => setOpen(false)}>Скасувати</button><button disabled={pending} className="rc-btn rc-btn-primary">{pending ? 'Збереження…' : 'Створити вправу'}</button></div></form></section></div> : null}</>;
}
